### ISSUE TITLE
Create Oscar asset that includes a complete runtime directory (including supported GCI files)

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/Jadeite#101]
It still takes forever to actually clone the Jade repository, while the Jadeite.exe asset is useful, I cannot properly pack the Jadeite without a complete runtime directory , so an asset that includes the full runtime directory would allow me to completely avoid cloning the repository ... it seems that @jgfoster has already include the runtime dir as an asset for Jade...

**Comment by jgfoster** [comment]
I learned (too late) that assets can be included in a "release" and do not need to be part of the "checkout." Thus, for several years I included both the executable (~2MB) and a zip of the entire distribution including all (now 94) DLLs (zip of 30+MB). The total git repository is now over 700MB, which is crazy. 

My advice would be that when Jadeite gets moved from ericwinger to gemtalk (or sooner!), that you not fork or clone, but start from scratch. You are inheriting a lot of cruft with jgfoster/jade.

**Comment by dalehenrich** [comment]
That is the plan, but it is even easier to download the runtime dir if is an asset ... or am I missing something.

**Comment by jgfoster** [comment]
Making a full runtime environment an asset is the right approach (as I understand things now; but I'm still learning!).

My comment about the size of the repository was purely in response to your observation about how long it takes to clone the repository, not to suggest anything else.

**Comment by dalehenrich** [comment]
I'm bumping this issue again as I copy an old Jadeite directory so that I can download Jadeite-Oscar-3.0.41 ... friendly reminder that we should make the full runtime directory as an asset ... I have a golden directory on disk on my laptop with all of the required runtime assets and it would be nice not to have to maintain that ...

**Comment by ericwinger** [comment]
@dalehenrich  I've added runtime.zip as an asset to Oscar 3.0.41. I'll try to remember to add it to every tagged release & pre-release going forward. 

If I forget, you can always get the runtime environment for Jadeite from here. 
https://github.com/GemTalk/Jadeite/tree/master/runtime

**Comment by dalehenrich** [comment]
I didn't see that you had actually added it to 3.0.41 ... the bug was still open until just now:) ...

When I downloaded the runtime dir, I noticed that it has a lot of cruft in it:
![image](https://user-images.githubusercontent.com/623951/46755565-4164c680-cc7a-11e8-977a-d8bbce7fb48e.png)
note the 233.4kB errors file (this file really should be deleted) and the two `.stb` files should also be nuked ... with the next release I will update the packing script to download the runtime directory from the resourece (so yes please try to remember to do this ... don't you have a script that does this?) and I can get rid of my golden copy ...

I'm reopening because of the cruft in the runtime, dir but if you prefer a separate bug let me know ...

**Comment by ericwinger** [comment]
> I didn't see that you had actually added it to 3.0.41

Yes, I just added it this morning. 

> (so yes please try to remember to do this ... don't you have a script that does this?)

The Jadeite.exe has to be created from within the Dolphin image so, no, there is not a script to do that. A script to copy the Jadeite.exe & runtime.zip to github as an asset could be created I guess. Although I'm not sure how to do that just yet. 

> I'm reopening because of the cruft in the runtime, dir but if you prefer a separate bug let me know ...

I put up a new runtime.zip without the .errors & 2 .stb files. Please reopen and let me know if you find more cruft. 

(Edited to make my comments visually distinct)

**Comment by dalehenrich** [comment]
Looks perfect! Thanks!
