### ISSUE TITLE
debugger, 'Executed Code'  stack frame, pop up menu items

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#103]
Of course it doesn't really make sense to have the Executed Code frame selected and try the popup menu item browse frame method, or other other menu items either.  But if you do...

- [x] Browse frame method gets an error dialog UndefinedObject DNu asString 
- [x] if there's a breakpoint in the method called by the executed code, the first time you try browse framemehod, it then puts up an error dialog 
---------------------------
GemStone Error #6005
---------------------------
a Breakpoint occurred (error 6005), Method breakpoint encountered.
GsProcess(oop=53651201, status=debug, priority=15, 
   Cabbage >> trySomething: @5 line 7
   Executed Code  @3 line 1
   GsNMethod class >> _gsReturnToC @1 line 1
)

- [x] browse senders/implementors get walkback, UndefinedObject DNU asSymbol.

**Comment by LisaAlmarode** [comment]
In 3.0.20, I can't even use the pop up menu when on the Execute Code frame.  This particular case is when there's a breakpoint in the method.  

In the Executed code frame, try to pop up a menu items and see:

First error:
Error while processing error: UndefinedObject does not understand #asString

second error;
GemStone Error #6005

a Breakpoint occurred (error 6005), Method breakpoint encountered.

GsProcess(oop=54420225, status=debug, priority=15, 
   Cabbage >> trySomething: @5 line 7
   Executed Code  @3 line 1
   GsNMethod class >> _gsReturnToC @1 line 1
)

**Comment by ericwinger** [comment]
I just disabled the three menu options when there is no method selector in the frame. I'm not even sure what we'd navigate to. 

Fixed in 3.0.21

**Comment by ericwinger** [comment]
Added debugger test ``testStackMenuEnablement``

**Comment by LisaAlmarode** [comment]
Doesn't seem fixed in 3.0.21; at least, per my second comment, the popup is broken such that I can't verify individual menu items are present or working. 

execute String foo
Open debugger
select Executed Code frame
Try pop-up menu in code pane
see error dialog and then another

![image](https://user-images.githubusercontent.com/13142166/44757562-aefece00-aae4-11e8-8ebc-9c7245ef519f.png)

**Comment by ericwinger** [comment]
@LisaAlmarode I believe this is working. When I tried the reproduction case, the menu worked fine. 

fyi - When I turned off the new debugger and tried the reproduction case, I got error messages such as the one you're seeing. 

Could you recheck this?

**Comment by ericwinger** [comment]
Actually, cancel @LisaAlmarode. It appears the bug is actually in the runtime only. I'll investigate tomorrow.

**Comment by ericwinger** [comment]
There is a path in the runtime only that finds the method service selector nil, then tries to send asString in the ``name`` method. Now we return an empty string in that case which seems reasonable. Fixed in 3.0.25.
