### ISSUE TITLE
Inspector: be nice to be able to apply changes to the object

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#104]
I'm used to being able to modify objects in inspectors.  If I use the save pop-up menu item in the right side of an inspector, I get a dialog "save document as..." which is not at all what I have in mind.

Inspect:
  Dictionary new at: #abc put: 'hello'; yourself

try to edit the string 'hello' and save.

Perhaps at least this shouldn't have the save on the menu... or just be read only.  I can attempt to edit by executing code in the inspector but it doesn't update the display.

**Comment by ericwinger** [comment]
This would be a handy feature. Left the dialog but added a dialog saying it isn't implemented yet.

**Comment by ericwinger** [comment]
Should be able to save elements of an object now. Done over a series of commits in Jadeite & Rowan. Last commit was https://github.com/GemTalk/Jadeite/commit/b0c2a56a7b8e09b2e964f319ea74dfacedddee18

**Comment by LisaAlmarode** [comment]
Adding something to a dictionary, specifically, is a little weird, since it only adds one field, the key.  If you enter an association, the whole association is the key.  This isn't a big deal, but the API is confusing.  I can't examine the keys, which is a little more annoying.

If you enter characters without # or quotes, it walks back.  If the object is not resolvable, assuming it's a string is probably better behavior.  

Not tested yet on complicated custom collections - I'll need to change stones and upgrade plantis.  So I'm reopening, but I don't have anything that is required for December.

**Comment by ericwinger** [comment]
@LisaAlmarode - I agree that adding to a dictionary is different than adding to a standard collection. However, by adding a key, then saving a change to that key's value in the code pane, one can add an element. It's two steps but at least is possible. 

The added key should compile in the context of the dictionary. That was a bug which will be fixed in prerelease 4.

**Comment by ericwinger** [comment]
Adding key now compiles in dictionary's context

**Comment by LisaAlmarode** [comment]
In 92-4, with a dictionary

-> Add Object, enter a random string without quotes results in "a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor".   I think this is a different error but it's not "working".

-> Add Object, entering 'a' -> 2 results in adding the key 'a'->2 with a nil value.  It doesn't seem to have changed from 92-3.

These do not need to be addressed; low-priority nice-to-haves, not really bugs.
