### ISSUE TITLE
Various spurious dialogs and walkbacks on filein errors

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#118]
If you select and file in text (e.g., the transcript workspace pop up menu, or a string inspector Jade menu item file in, you get nonrowanized code, per bug 70. 

However, if the section being filed in has syntax issues... weird stuff happens.

- [ ] if it's a string (with quotes around the filein code), it opens two dialogs, a Please wait... with the first line of the string, and a Note with the apology about not converting to oop. 

- [ ] if you say, misspell category, you get the above two issues but when you close the top one you get a note saying nil DNU asSymbol, and it opens a new workspace holding the stack trace.  This is a little too messy to look the other way.

**Comment by ericwinger** [comment]
Looks like the gemstone base methods like fileOutClass haven't been rowanized yet. Will need those before this can be fully fixed. GemTalk/Rowan#351

**Comment by LisaAlmarode** [comment]
I'm not sure what exactly I was complaining about; error filing in random text makes sense.  Presumably whatever the problemw as will be sorted out when testing the newly supported filein-out in 3.2.12 and new issues can be filed.
