### ISSUE TITLE
Package Browser (3.0.20): hierarchy class view and classes defined in different pacakge oddity

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/Jadeite#121]
Here's a screen shot:
![image](https://user-images.githubusercontent.com/623951/44677815-c1491100-a9eb-11e8-9016-80658620cd13.png)
... and these things are not quite right
- [x] non-package class (RwGemStoneSpecification) not highlighted correctly
- [x] `Go to Defining Package` is not functional
... cannot compile method in this view either ... defaultUserSessionMethodsForExtensions is an IV in RwGemStoneSpecification:
![image](https://user-images.githubusercontent.com/623951/44678256-dd997d80-a9ec-11e8-95dc-5f85f3e7fd97.png)
... and compiles correctly when defining package is selected (in case it matters, I did have two package browsers open):
![image](https://user-images.githubusercontent.com/623951/44678433-32d58f00-a9ed-11e8-8da7-bbac719c9a31.png)

- [x] allow method compilation for classes not in selected package

**Comment by ericwinger** [comment]
Part 3 is fixed in Oscar 3.0.24. Others were fixed in prior versions.
