### ISSUE TITLE
Debugger opens second debugger, loses stack in original debugger

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#126]
In 3.0.22, I'm trying the restart when I'm in a block context.  This gives an walkback on "Cannot trim stack to a block in recompiled method.".  This is a little misleading since I'm just doing a restart, I have not compiled anything or made any code edits... but it's not entirely unreasonable that this doesn't work. 

![image](https://user-images.githubusercontent.com/13142166/44808148-5250f100-ab80-11e8-880b-5cb498e4374e.png)

However, if I select debug on the walkback, it opens a debugger with the stack for "a InternalError occurred (error 2023), Cannot trim stack to a block in recompiled method"

AND my original debugger on my code is lost; that one is also now showing the contexts for the 
"a InternalError occurred (error 2023), Cannot trim stack to a block in recompiled method", though the line at the top still says "a Breakpoint occurred (error 6005), Method breakpoint encountered."

![image](https://user-images.githubusercontent.com/13142166/44808157-5b41c280-ab80-11e8-9752-67e3b36de5f7.png)

**Comment by ericwinger** [comment]
Upon opening the second debugger, a selection was triggered that sent #selectedProcess to both debuggers.  Needed to make sure that we only update the stack if the oop of the process in the debugger matches the oop of the process being updated.  Fixed in Oscar 3.0.24
