### ISSUE TITLE
Abort transasction doesn't remove up added, uncommitted class

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#127]
If I add a class in the Projects browser, and abort transaction, I'd expect the class to go away.  But it's still there.  Clicking on it gets a walkback:

a MessageNotUnderstood occurred (error 2010), a UndefinedObject does not understand  #'comment'
MessageNotUnderstood >> defaultAction @2 line 3
MessageNotUnderstood (AbstractException) >> _signalWith: @5 line 25
MessageNotUnderstood (AbstractException) >> signal @2 line 47
UndefinedObject (Object) >> doesNotUnderstand: @9 line 10
UndefinedObject (Object) >> _doesNotUnderstand:args:envId:reason: @7 line 12
RowanClassService >> basicRefreshFrom: @4 line 5
RowanClassService >> refreshFrom: @2 line 3
RowanClassService >> updateClass @4 line 5
RowanClassService >> update @2 line 3
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @6 line 11
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
This is issue https://github.com/GemTalk/Rowan/issues/349. 
Dale has a jadeite issue similar to this for tracking as well. https://github.com/GemTalk/Rowan/issues/348

**Comment by LisaAlmarode** [comment]
This bad behavior is still present in 3.0.26 with rowan a2093df.
