### ISSUE TITLE
UndefinedObject does not understand #gciCallInProgress

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#13]
Since my vpn connection is not very reliable I lose sessions a lot. This results in a walkback: 
    UndefinedObject does not understand #gciCallInProgress

It would be nice if this was handled a little better.

Current ERRORS follows this pattern

{051504C4: cf 051504A5, sp 051504D8, bp 051504C0, ip 4, Object>>doesNotUnderstand:}	receiver: nil 	arg[0]: Message selector: gciCallInProgress arguments: #()
{051504A4: cf 05150489, sp 051504B8, bp 051504A4, ip 4, GciSession>>isCallInProgress} 	receiver: a GciSession
{05150488: cf 0515046D, sp 0515049C, bp 05150488, ip 3, RowanTranscript(JadeTranscript)>>onIdleEntered} 	receiver: a RowanTranscript

**Comment by ericwinger** [comment]
This may be a tough one. If you give me a use case and I *might* be able to code around it.

**Comment by ericwinger** [comment]
@LisaAlmarode This appears to have been fixed some time ago. Do you still see this problem? 
https://github.com/GemTalk/Jadeite/commit/1e25e20d46cbd133d483d8533e198b19764fe499

**Comment by LisaAlmarode** [comment]
Close as old and probably obsolete.
