### ISSUE TITLE
Browse references from hierarchy view wrong

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#136]
We were getting the class name from the wrong list. Fixed in Oscar-3.0.27

**Comment by LisaAlmarode** [comment]
Not reproducing, but no reproduction case to verify.

**Comment by ericwinger** [comment]
Oh sorry. 

- Select a class in the class list. 
- Press hierarchy. 
- Select a different class. 
- Press Browse References. 
- Was browsing references to wrong class (class in class list, not hierarchy).
