### ISSUE TITLE
Hierarchy update interrupted causes walkback

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#137]
- Open two browsers
- select the same class in the class list (call them A&B)
- in B select hierarchy

Get walkback trying to find missing class. 

Fixed in Oscar-3.0.27

**Comment by LisaAlmarode** [comment]
I can't reproduce with given information in 3.0.26 or 3.0.27

**Comment by LisaAlmarode** [comment]
Eric didn't mark it closed and I didn't notice.
