### ISSUE TITLE
Cannot use CTL-S in method list browser (Oscar3.0.26)

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/Jadeite#138]
When I use `CTL-S` in method pane I get a `DC3` inserted instead of performing a save:
![image](https://user-images.githubusercontent.com/623951/45000147-53669180-af77-11e8-8a72-f81284ad178c.png)
The `save` menu item still functions ..

**Comment by dalehenrich** [comment]
Saw this in Oscar3.0.25 and upgraded to 3.0.26 to see if it was still present ... it is:)

**Comment by ericwinger** [comment]
Dolphin key bindings and menus are ... interesting. Should be fixed in 3.0.28.
