### ISSUE TITLE
Can no longer delete a method from method browser list (Oscar 3.0.26)

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/Jadeite#139]
![image](https://user-images.githubusercontent.com/623951/45000215-e0a9e600-af77-11e8-9f59-6383cadbd277.png)
I swear that there used to be a menu item that allowed me to delete selected methods ...

**Comment by ericwinger** [comment]
I believe you want `Remove Selected Methods...`

**Comment by dalehenrich** [comment]
Ah ... did it get moved from the bottom if the menu?

**Comment by ericwinger** [comment]
No, it's been there for quite awhile. 

However, in looking at the placement and name of the menu item, it has a few issues. It's close to the other Remove* item. It's higher in the list than on the projects browser and it's label is inconsistent. 

I think it should be consistent with the ``Remove method(s)..." item in the projects browser. I'm going to move it down farther in the list and relabel it which should improve readability. 

Change will be in 3.0.28.
