### ISSUE TITLE
Need better error when debugger save in block context

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#140]
When you are in a block context in the debugger, and edit the method and want to save, it doesn't work.  This annoys me a lot in GBS but I accept this.  However, the walkback in Oscar (3.0.26) is not helpful.

a ArgumentTypeError occurred (error 2094), reason:rtErrBadArgKind, expected a CharacterCollection
ArgumentTypeError (AbstractException) >> _signalWith: @6 line 25
ArgumentTypeError (AbstractException) >> signal @2 line 47
UndefinedObject (Object) >> _error:args: @15 line 11
UndefinedObject (Object) >> _errorExpectedClass: @2 line 5
UndefinedObject (Object) >> _validateClass: @4 line 6
Symbol class >> _existingWithAll: @2 line 10
SymbolList >> resolveSymbol: @4 line 9
SymbolList >> objectNamed: @2 line 8
RwGsImage class >> objectNamed: @3 line 6
RwGsPlatform >> globalNamed: @3 line 5
Rowan class >> globalNamed: @3 line 5
RowanClassService >> classFromName @2 line 3
RowanClassService >> packageIsDirty @2 line 4
RowanClassService >> arePackageAndProjectClean @2 line 3
RowanClassService >> servicePerform:withArguments: @2 line 3
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @10 line 12
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
Added a message in the debugger warning that the user can't save in an exec block. 

Fixed in 3.0.28.
