### ISSUE TITLE
Debugger text pane pop-up menu save behavior isn't right

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#141]
In the debugger if you are not on the top frame, and edit the method, and save... the right click pop-up menu item save does not trim the stack.  The saved frame does show the new version of the method but the block context at the top of the stack shows the original version.

The control s and the File menu item save do trim the stack, so after the save you are on the top frame, and the new method contents are displayed.

**Comment by ericwinger** [comment]
Fix in Oscar-3.0.28
