### ISSUE TITLE
Preferences not discriminating regarding arguments

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#142]
The transcript write stickiness in #124 is working well.

However, transcript writes are not only disabled if I specifiy false; it appears that anything other than true works... for example the following all have the same behavior:

transcriptEnabled false
transcriptEnabled yes
transcriptEnabled no
transcriptEnabled 1
transcriptEnabled 0

This is better than erroring and only the smallest issue in this case... but as the preferences features may be  expanded this may matter.

**Comment by ericwinger** [comment]
@LisaAlmarode - Preferences were overhauled. Is this still an issue?

**Comment by LisaAlmarode** [comment]
Arguments of 1, 0, nil, 'true', 'false' do not error in the preferences file as of 3.0.92-2, but they always set the value to false, which seems not quite correct - an invalid argument should fall back to the default.  However, I'll close this since this is small fry.
