### ISSUE TITLE
Add method as non-system user in dictionary view without the magic expression

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#144]
I have a user Lisa with  CodeModification, UserPassword and OtherPassword, 
but I have NOT executed this magic:
  GsPackagePolicy current enable. UserGlobals at: #rowanCompile put: true. System commitTransaction.

This may or may not still be required, but everything seems to work fairly reliably in the projects browser without it... it would be better to have some kind of visible warning if it's not executed, that there be dragons.

If you add a method in the dictionaries browser, the new method is not added to the project.
It will show up in the project browser, but if you click on it in the project browser, you get a walkback:

a UserDefinedError occurred (error 2318), reason:halt, Internal error -- no existing LoadedMethod fo
UserDefinedError (AbstractException) >> _signalWith: @5 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwGsSymbolDictionaryRegistry (Object) >> error: @6 line 7
[] in  ExecBlock0 (RwGsSymbolDictionaryRegistry_Implementation class) >> addRecompiledMethod:instance: @2 line 26
IdentityCollisionBucket (AbstractCollisionBucket) >> at:ifAbsent: @10 line 10
IdentityKeyValueDictionary >> at:ifAbsent: @15 line 13
RwGsSymbolDictionaryRegistry_Implementation class >> addRecompiledMethod:instance: @15 line 23
RwGsSymbolDictionaryRegistry_Implementation class >> addNewCompiledMethod:for:protocol:toPackageNamed:instance: @8 line 9
RwGsSymbolDictionaryRegistry >> addNewCompiledMethod:for:protocol:toPackageNamed:implementationClass: @2 line 5
RwGsMethodAdditionSymbolDictPatch >> installMethod @5 line 4
[] in  ExecBlock1 (RwGsPatchSet_254) >> updateMethodDictionaries @6 line 18
[] in  ExecBlock1 (Set) >> do: @2 line 11
[] in  ExecBlock2 (KeyValueDictionary) >> keysDo: @2 line 7
KeyValueDictionary >> keysAndValuesDo: @23 line 20
KeyValueDictionary >> keysDo: @2 line 6
Set >> do: @3 line 11
RwGsPatchSet_254 >> updateMethodDictionaries @5 line 14
RwGsPatchSet_254 >> apply @26 line 28
RwGsImage class >> applyModification_254:visitorClass:instanceMigrator: @10 line 9
RwGsImage class >> applyModification_254:instanceMigrator: @8 line 12
RwPrjLoadTool >> _loadProjectSetDefinition_254:instanceMigrator: @17 line 18
[] in  ExecBlock0 (RwPrjLoadTool) >> _doProjectSetLoad_254:instanceMigrator:originalProjectSet:processedClassNames: @2 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
RwPrjLoadTool >> _doProjectSetLoad_254:instanceMigrator:originalProjectSet:processedClassNames: @2 line 6
RwPrjLoadTool >> loadProjectSetDefinition:instanceMigrator: @3 line 7
RwPrjLoadTool >> loadProjectSetDefinition: @4 line 4
[] in  ExecBlock2 (RwPrjBrowserTool) >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta:inPackageNamed: @46 line 64
[] in  ExecBlock3 (RwPrjBrowserTool) >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta:inPackageNamed: @5 line 72
[] in  ExecBlock1 (RwAbstractTool) >> definitionsForClassNamed:ifFound:ifAbsent: @14 line 11
RwGsImage class >> loadedClassNamed:ifFound:ifAbsent: @9 line 11
RwPrjBrowserTool (RwAbstractTool) >> definitionsForClassNamed:ifFound:ifAbsent: @3 line 4
RwPrjBrowserTool >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta:inPackageNamed: @12 line 69
RwPrjBrowserTool >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta: @13 line 37
RowanSample1Test class (Behavior) >> rwCompileMethod:category: @9 line 4
[] in  ExecBlock0 (RowanClassService) >> compileMethod:behavior:symbolList:inCategory: @2 line 6
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
[] in  ExecBlock0 (RowanClassService) >> compileMethod:behavior:symbolList:inCategory: @2 line 6
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
RowanClassService >> compileMethod:behavior:symbolList:inCategory: @2 line 8
RowanClassService >> saveMethodSource:category: @18 line 11
RowanClassService (RowanService) >> servicePerform:withArguments: @2 line 2
RowanClassService >> servicePerform:withArguments: @4 line 4
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @10 line 12
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
I would expect any method compiles in the project browser to work. I would expect method compiles to work in the dictionary browser, but only for rowan-ized classes. 

I haven't spent any time making non-rowan compiles more elegant or easier as it is my hope that the GemStone base code will be rowan-ized sooner rather than later. Then, we can remove the ``#rowanCompile`` flag entirely. 

I'm not sure what work I should do to better support non-rowan compiles in Oscar, if any. 

@dalehenrich - What's your feeling?  Should I do any more work to support compiling methods outside of rowan in Oscar? If so, what should be done?

**Comment by ericwinger** [comment]
I can confirm that setting ``rowanCompile`` to false then saving a method in a rowan class via the dictionary browser does not appear as a changed method in the changes browser. 

I'll need some guidance as to what, if any, changes I should make to Jadeite from @LisaAlmarode & @dalehenrich . I assume this becomes a mute point after the base gets rowanized.

**Comment by ericwinger** [comment]
The rowanCompile flag has been removed so I don't think this is an issue any longer. 
https://github.com/GemTalk/Rowan/commit/5a8a3b5bbd36ed0a3dd74ee29ebc368a1894ba27

**Comment by LisaAlmarode** [comment]
I believe in 3.0.78 that I can run without #rowanCompile and with GsPackagePolicy current enabled = false, and save methods and creates classes and suchlike.  OtherPassword still required for some operations cf issue #551
