### ISSUE TITLE
Abort doesn't work right with loaded-but-uncommitted project

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#146]
In the project browser with 3.0.27. 
If I clone and load a project, and do not commit; abort does not remove the project from the project list pane, which is weird... but possibly OK. 

If I have added a class to the loaded-but-not-committed project, then abort does not remove the class or method, 

Interestingly, neither the loaded-but-uncommitted class nor the added class are accessible in the dictionary browser.

If I edit an existing method to reference the new class, and click on a different method and back onto the edited method, I get a walkback.  It appears to be trying to perform #'setBreakPointAt:in:' with an empty collection. 

a MessageNotUnderstood occurred (error 2013), reason:rtErrCantPerform, a UndefinedObject does not un
MessageNotUnderstood >> defaultAction @2 line 3
MessageNotUnderstood (AbstractException) >> _signalWith: @5 line 25
MessageNotUnderstood (AbstractException) >> signal @2 line 47
RowanMethodService (Object) >> _error:args: @15 line 11
RowanMethodService (Object) >> cantPerform:withArguments: @8 line 9
RowanMethodService (Object) >> _perform:env:withArguments: @7 line 24
RowanMethodService (Object) >> perform:withArguments: @4 line 16
RowanMethodService (RowanService) >> servicePerform:withArguments: @2 line 2
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @10 line 12
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
@LisaAlmarode I'm pretty sure that this is related to [https://github.com/GemTalk/Rowan/issues/349 ](url).  Closing as any number of bad things can happen when the two symbol lists get out of sync. 

Reopen if you feel there is more going on.
