### ISSUE TITLE
Need strategy for client and server upgrades

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#147]
Eventually, we will have different released versions of Jadeite. We will need a strategy for how to manage this. 

Brain dump of some issues to handle: 
- How to handle Jadeite-Rowan services api changes?
- New api's? 
- Deprecated api's? 
- Possibly create a "minimum Rowan version" in Jadeite - ie you can't login unless you have this version of Rowan. 

This will need to involve all the pieces of Edelweiss so assigning @dalehenrich and @LisaAlmarode for discussion.

**Comment by ericwinger** [comment]
Additional data point - The informal plan has been to separate RowanServices packages into their own project so they can be loaded independently of Rowan.

**Comment by LisaAlmarode** [comment]
I think this has been resolved with the services and version notifications, and this bug isn't of value any more.

**Comment by dalehenrich** [comment]
One part of the solution/toolset could involve loading multiple versions of RowanClientServices into in image (on demand or explicitly) and Jadeite could pick the latest version that is available … this topic is worth discussing when all three of us are in office?
