### ISSUE TITLE
Poison pill for Jadeite alpha

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#148]
The Jadeite alpha which was released in May will not work with the rowan services & JadeServer classes in Oscar. 

We need to (potentially) add a poison pill so that the user cannot login to an Oscar-rowan server with the Jadeite alpha (2.0.1).

**Comment by ericwinger** [comment]
@dalehenrich Since no one is using Jadeite Alpha anymore, should we close this issue?

**Comment by dalehenrich** [comment]
... not for Alpha1, but do we need one for Jade? There is some public information about how to install Jade persistently in an image that would cause problems for Jadeite and if anyone were to try to use Jade in a Rowan image  (changing Rowanized methods or classes) that would definitely cause trouble ... I would think that creating a object that cannot be written to in one of the spots used by Jade might do the trick?

don't reassign to me unless you need it for your peace of mind ... I don't look at issues assigned to me on the Jadeite list in the normal course of business, but I do monitor the github mail traffic and that is usually how I recognize that I need to respond:)

**Comment by ericwinger** [comment]
@dalehenrich I assigned to you for a response to my question. Nothing more. 

Putting in the poison pill for Jade is a good idea as much of the Jade service code would get overwritten. I'll reassign back to myself and mark as an April fix.

**Comment by ericwinger** [comment]
@dalehenrich I looked at the JadeServer installation [code](https://github.com/jgfoster/Jade/blob/9234b495723f360c39636b27fe4ff0fab7e18d00/sources/JadeServer.cls#L784) and Jade creates a new symbol list on the server then installs the JadeServer client code into the that symbol list. If persisted, this could make Jadeite non-functional as indicated earlier in this issue. 

In thinking about a poison pill ... JadeServer is currently installed in UserGlobals. Installing it in Globals would eliminate any potential damage by anyone but SystemUser. 

Another thought ... If Rowan controls all class definition compiles then couldn't Rowan just throw an error if JadeServer was recompiled? Any attempts to login by Jade would fail and code integrity would be preserved.

**Comment by dalehenrich** [comment]
The "poison pill" idea is to force an error during installation so that the user does not get the idea that Jade can be safely used, or is inadvertently logging into a Rowanized stone ... eventually it will be legal to use the "standard" class and method creation calls at which point it won't hurt for Jade to be installed, so this is only an "issue" as long as a Rowanized stone is "vulnerable" ... if there is no practical way to prevent installation, then we'll just have to take our chances ...

**Comment by ericwinger** [comment]
@dalehenrich Is this still needed? We have a form of poison pill in that versions are checked on login - giving a warning message if the user is out of sync.

**Comment by dalehenrich** [comment]
the alpha jadeite is no longer an issue

**Comment by ericwinger** [comment]
Retiring
