### ISSUE TITLE
Method modifications

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#149]
Although a new changes browser is needed which uses modifications (#123), a helpful first step will be to display method-level changes in the projects browser. 

``RowanMethodService`` already knows his package and project name. Using the code below, we can dive into the project modifications and keep diving until we find method source changes (if any). Those could be displayed in the Comparison tab. 

To get project level differences: 

```
	| projectSetDefinition loadedProjectSet diff |
	projectSetDefinition := Rowan projectTools read
		readProjectSetForProjectNamed: 'RowanSample1'.
	loadedProjectSet := projectSetDefinition deriveLoadedThings
		asProjectDefinitionSet.
	diff := projectSetDefinition compareAgainstBase: loadedProjectSet.
	diff isEmpty ifTrue:[^self].
	diff 
```

A few thoughts: 

- ignore movedClasses & movedMethods
- ignore package level properties changes
- Elements modifications can be sent ``isEmpty``. 
- starting with the project differences dive down to the method level difference. At any level, if the modification returns true to isEmpty, there is no difference. 
- before and after are relative to the way ``compareAgainstBase:`` is sent (the example above would produce before = disk)
- There are two hierarchies - ``RwElementsModification`` and ``RwModification``

**Comment by LisaAlmarode** [comment]
This has been implemented
