### ISSUE TITLE
Go to defining package -> Not found: a BlockClosure

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#150]
In projects browser, it sometimes doesn't respond well to the classes pane menu item go to defining package, if the package is in a different project or if the class is not rowanized (e.g. extensions to server methods).  I'm logged in as DataCurator to 3.0.28 with latest rowan.

E.g. Rowan | Rowan-Tools-Kernel | CypressDefinition
or Rowan | Rowan-GemStone-Kernel | ByteArray

**Comment by ericwinger** [comment]
One case was a class that was in a different project. The other was non-rowanized. Both fixed with one change in 3.0.29. Test added.

**Comment by LisaAlmarode** [comment]
This class problem fixed; the same problem occurs with methods.

Rowan | Rowan-Tools-Kernel | CypressDefinition and select isClassDefinition.

**Comment by ericwinger** [comment]
re-Fixed in 3.0.31

**Comment by LisaAlmarode** [comment]
Generally looks good.  If you go to defining package on a non rowan class it opens a dictionary browser.  If you go to defining package on a non rowan method it does nothing.  But I don't think this is worth quibbling over.
