### ISSUE TITLE
Problems with multiple tabs in project browser

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#158]
Although using multiple tabs in the projects browser works, it hasn't been thoroughly tested. 
Because browsers can update each other, there may be lurking problems. 

Need a thorough review with new issues opened for anything found. 

fyi - I suspect a lot of these bugs can be found by opening two side-by-side browsers.

**Comment by LisaAlmarode** [comment]
one window with two project browsers. 
- [ ]  If I add a category in one, it's added in both.  If I move a method to the new category, the change isn't in the other one.

add category and method are fine.

- [x] If I remove that method, it doesn't remove it in the other one. If I try to remove it a second time in the second browser, I get a walkback.

- [x] if I have the same method selected in both, and edits in both, and I save in one of them, it updates and I lose the edits in the other.

add and remove class are okay,

**Comment by LisaAlmarode** [comment]
The only thing that still occurs is that the category is added in both, and I think that's OK.
