### ISSUE TITLE
Menu items matching icon bar operations

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#159]
I just sort of noticed the icon bar, and it has functions enabled that are disabled in the menus, which isn't right.  

The icon bar includes:
- abort,  on Jadeite menu, okay.
- commit, on Jadeite menu, okay.
- new workspace  
   - [ ]     this is greyed out on Jadeite menu - either both or neither should be enabled
- add tab  
   - [ ]     this is greyed out on Jadeite menu; since this is the only way to get a tab, it should be enabled.
- (greyed out) browse users
- maximize code
   - [ ]    should be somewhere, although not critical
- sunit browser 
    I question if this is working... it's always empty for me.
- (greyed out) history back
- (greyed out) history forward

**Comment by ericwinger** [comment]
Fixed in 3.0.32.  Note - for some reason I couldn't check off the task items. Perhaps it's something in the way the underlying text is formatted.

**Comment by LisaAlmarode** [comment]
Yes, SUnit was fixed separately.  Menu items look fine now.  As for the checkboxes... not sure the bullets were a good idea to mix with the boxes.
