### ISSUE TITLE
Review/revisit semantics of font color/italic/bold etc. 

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#16]
- Old Jadeite had everything dirty as bold italic.  This seems to be missing in some places under some circumstances.
- The purple indicating ownership works but is not visible when selected.

This issue is a placeholder for a full review.

**Comment by ericwinger** [comment]
I'm not sure I'm qualified to do a full review. I'd prefer that @LisaAlmarode take this on. Reassigned back to her. 

One note ... on the method list display, I'm reserving italics for when https://github.com/dalehenrich/Rowan/issues/276 is resolved.

**Comment by LisaAlmarode** [comment]
Reviewed in 3.0.22 for bold/italic = dirty consistency.  Will look at reds and purples separately.  

The bold/italics issues have two parts. 
 - One is that I don't think there is method level dirtiness marking, currently, per the rowan bug. 
 - The other issue, which can be addressed now in Jadeite, that that while some actions (e.g. edit a method) update the package and project fonts, most don't.  

-----------------

edit a method 
    class, category and method are in ordinary font (should be bold italic)
     project and package are correctly bold italic.

Move method to a different category, or remove a method. 
     Nothing is bold italic.
     If I refresh project, the Project and Package become bold italic.  

edit class definition (that is, modify instance variables), or update class comment  
   Nothing is bold italic.  
   click away and back, the package becomes correctly bold italic
    on project refresh, becomes correctly bold italic
    The class remains incorrect ordinary font.  
    (category and method are correctly in ordinary font)

Add or remove class 
	does not make anything dirty.  Should make package and project dirty.
	If I click in the packages pane it turns dirty.  
     It takes refresh to set the project to bold italic. 

Add package - behaves correctly.

Add category - reasonable that this has no effect on dirtiness.

**Comment by ericwinger** [comment]
The "edit a method" checkbox won't be available until we get method level dirty in Rowan. https://github.com/GemTalk/Rowan/issues/276.  I've submitted https://github.com/GemTalk/Jadeite/issues/130 to cover it. 

I believe the rest are going to be fixed in Oscar 3.0.23

**Comment by LisaAlmarode** [comment]
[ ]  Removing method does not update project and package fonts correctly.

[ ] Removing a class does not  update project and package fonts correctly.

**Comment by ericwinger** [comment]
A refactoring bypassed the invalidation of the views. The fix this time should be general enough to redraw the views after most any action by the user that changes the dirty state. Redraws are fast. 
Fixed in 3.0.30

**Comment by LisaAlmarode** [comment]
In 3.0.30, as SystemUser, it's not looking any different... after a remove method or remove class, I have to click in the package or project pane before it refreshes.

**Comment by ericwinger** [comment]
Fix lost in fix for #128.  Restored in 3.0.31 - should refresh across browsers now.
