### ISSUE TITLE
disable filein/fileout

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#160]
As long as filein/fileout are not rowanized, it would be better to disable the menu items.  You could say "Filein/fileout are not Rowan-ready in this version"

the project browser 
  - [x] class
  - [x] category
  - [x] and method menu bar and pop up menus
and the dictionary browser 
  - [x] sym dict filein
  - [x] sym dict fileout
  - [x] class
  - [x] method menu bar and pop up menus

**Comment by ericwinger** [comment]
Fixed with the text suggested. The list was helpful of menu item locations was helpful.
