### ISSUE TITLE
Debugger menu quibbles

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#167]
- [x]  I had trouble finding the non-pop up menu save option since it was on the debugger File menu.  Seems more logical to be on the Edit menu. 

- [x]  I don't think save should be enabled on the menus, unless you've actually edited the text.
However, if you save when there are no text changes, it doesn't actually save; my breakpoint is still there; though it does trim the stack. 

- [ ] The floating help for the icon bar hourglasses in the debugger ought to use the same terms as the menu. 
E.g, the first one, the hourglass with the blue blob, says "Print results of selection or line" which doesn't map in my brain immediately to Display, and the second says "Evaluate" as oppose to Execute.

**Comment by ericwinger** [comment]
Fixed in 3.0.34
