### ISSUE TITLE
Recursion to horrible crash

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#168]
There is a known situation that arises when a debugger or inspector encounters a breakpoint in an asString method.  

I thoughtlessly stuck a breakpoint in an asString method.  The sky fell.  Oscar opened a bunch of windows then crashed.

While I don't think perfection is in range just now, a slightly more graceful way to fail would be nice.

**Comment by ericwinger** [comment]
@LisaAlmarode I could see improper placement of a halt in ``asString`` having a whole host of behavior problems depending on which asString was affected. Any chance you remember which asString was to blame?  And what you did to open the debugger?

**Comment by LisaAlmarode** [comment]
Since I've been attempting to test inspectors and find a workaround for #433, I've encountered similar issues twice since lunch.  Crashing the IDE is not very nice.  Making this a little more prominent.

For a class similar to the one in the example in 433, I put a halt or breakpoint in the size method.  I
I ran tests. I lost everything.

**Comment by LisaAlmarode** [comment]
This issue appears fixed, or at least much much better. I tried a couple of times to cause breakage in the inspector, and it just put errors in the inspector.  I got a whole series of walkbacks when I did direct call to recursion, and there were a lot; but it eventually displayed a dialog and while closing the walkbacks was tedious, my session was fine.
