### ISSUE TITLE
Debugger menu option Browse Class broken

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#169]
If I've got a Rowan class selected in the debugger and I try to Browse Class, I get an error:
  Error while processing error: UndefinedObject does not understand #parentPresenter

If it's a base class I get an error:
  Class 'String' not found!!

**Comment by ericwinger** [comment]
Fixed in #3.0.30 
Browse Class in debugger pane and method list source pane should now use identical working code. Test added for debugger part of fix.
