### ISSUE TITLE
Editing methods to create new method and updating created method gets errors

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#170]
In 3.0.28 as DataCurator, I have been editing methods to create new ones, and updating contents, and I am inevitably getting walkbacks, which are hard to reproduce.  The following case reproduces reliably for me.

I have a class with four instance methods, each one contains just ^5
 another
 interesting
 test
 try

edit "test" to "pest" and save.  pest it is at the bottom; click on each method in the pane, bottom to top, then back onto pest. 

edit pest contents to ^55, and save.  Again, click on each method in turn, then back onto pest. 

edit pest contents to ^55 + 1, and save.  Click on each method, then back onto pest. 

See walkback. In this one, the RowanMethodService ivar oop is 20.  I suspect that oop ifNil: is not expected oop to be 20.  

a MessageNotUnderstood occurred (error 2010), a UndefinedObject does not understand  #'selector'
RowanMethodService >> initialize:organizer: @4 line 5
RowanMethodService >> update @8 line 5
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @6 line 11
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1

------------------------

I also often see the following stack.  In this one, looking in the debugger, the method arg aGsNMethod is a ClassSet containing  GciTransportError.

a MessageNotUnderstood occurred (error 2010), a ClassSet does not understand  #'selector'
MessageNotUnderstood >> defaultAction @2 line 3
MessageNotUnderstood (AbstractException) >> _signalWith: @5 line 25
MessageNotUnderstood (AbstractException) >> signal @2 line 47
ClassSet (Object) >> doesNotUnderstand: @9 line 10
ClassSet (Object) >> _doesNotUnderstand:args:envId:reason: @7 line 12
RowanMethodService >> initialize:organizer: @4 line 5
RowanMethodService >> update @8 line 5
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @6 line 11
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
Jadeite wasn't always updating the selected method after a compile. This change should take away the weird animation when refreshing the method list, as well. 
Fixed in #170. Required fix for #128 first. Added test.
