### ISSUE TITLE
Project menu quibbles

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#171]
Between the Console pane popup menu and the Project Browser popup menu there are inconsistencies in the use of ... following the menu item.  As I understand, "..." implies a further selection, that does not include a confirmation dialog.

On console, 
- [x] Load, Unload, Pull from Git, Push to Git, Write should remove the ...

On project browser,
- [x] Pull from Git, Push to Git, Changes, and Write should remove the ...

On other related menus:

- [x] Find Class should be on the Jadeite menu, and not on the project and package menus, since it does not find within the project or package. 

- [ ] add package is on the package menu, which is weird since it's a project operation... I think it should be on the project menu.

- [x] the "save" in the Save Package ... on the package menu doesn't make sense.  You could renamed to Write Package perhaps (still a no-op), or just remove it.

- [ ] The package menu > Unload Package similarly is confusing... it could be renamed to Remove Package (still a no-op), as a placeholder.

**Comment by ericwinger** [comment]
>  add package is on the package menu, which is weird since it's a project operation... I think it should be on the project menu.
@LisaAlmarode I don't disagree with you, however I'd like to leave it on the package menu for three reasons. 

- One - Project & Package are similar names and I think it would be possibly misread as Add Project. 
- Add Package & Unload Package are nicely symmetric. 
- The package menu does package things. 

My vesting in this interest is very small so I could be persuaded to move it nonetheless.

**Comment by LisaAlmarode** [comment]
Since it's not implemented anyway, changing package unload doesn't matter.

- [ ] However, the add package thing... the symmetry is entirely grammatic, functionally they are very different; you don't have a package yet, when you go to add one.  I think package menu operations should be things that you do to a specific package.
Most of the project operations are things you do with a specific project.  Something you do to a specific project is add a new package to it.
If you are likely to get confused between package and project, then you are going to have lots of issues with Jadeite...

- [ ] This is why I also disagree with find class on the package menu since it finds a class anywhere, NOT just within the package.  You probably just missed fixing this since I hid it within the earlier sentence.

**Comment by ericwinger** [comment]
Fixed in 3.0.36.
