### ISSUE TITLE
Classes menu error if no Class selected

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#172]
If I have no class selected in a projects browser,

touching the Classes menu gets an error 

UndefinedObject does not understand #isTestCase

This also occurs if I move the mouse over the Classes menu after dropping down a different menu.

**Comment by ericwinger** [comment]
Enablement problem in the run tests button when no class selected. Fixed in 3.0.30 with test added to at least query all the menus for walkbacks.
