### ISSUE TITLE
new SUnit browser code walksback on short selector

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#173]
In a recent commit, I didn't account for method selectors < 4 characters when testing if a selector is a test method. 

Better solution will be in 3.0.31 by sending ``isTestMethod`` to RowanMethodService

**Comment by LisaAlmarode** [comment]
In 3.0.33, appears broken.  I added methods a, aa, aaa, aaaa, and testa to RowanSample1Test.  Now, I get a walkback when I try to open the SUnit browser:

a OffsetError occurred (error 2003), reason:objErrBadOffsetIncomplete, max:1 actual:4
OffsetError (AbstractException) >> _signalWith: @5 line 25
OffsetError (AbstractException) >> signal @2 line 47
Symbol (Object) >> _error:args: @15 line 11
Symbol (Object) >> _errorIndexOutOfRange: @2 line 6
Symbol (String) >> copyFrom:to: @11 line 16
[] in  ExecBlock1 (RowanBrowserService) >> packagesWithTests @2 line 8
Array (Collection) >> do: @5 line 10
[] in  ExecBlock1 (RowanBrowserService) >> packagesWithTests @3 line 6
Array (Collection) >> do: @5 line 10
RowanBrowserService >> packagesWithTests @6 line 5
RowanBrowserService (RowanService) >> servicePerform:withArguments: @2 line 2
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @10 line 12
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
Required a server side fix so pickup Rowan Oscar branch 3.0.34 when it's tagged.
