### ISSUE TITLE
Class menu item run tests broken

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#178]
Logged into 3.0.33 as DataCurator,  RowanSample1 loaded.  Select class RowanSample1Test.

The class menu item run tests produces a walkback.
I can run tests just fine from the Sunit tab, so it's not a userId problem per se.

a LookupError occurred (error 2096), reason:assocErrNoElementsDetected, detect: was sent to a collec
LookupError (AbstractException) >> _signalWith: @5 line 25
LookupError (AbstractException) >> signal @2 line 47
IdentitySet (Object) >> _error:args: @15 line 11
IdentitySet (UnorderedCollection) >> _detect: @13 line 9
IdentitySet (UnorderedCollection) >> detect: @15 line 23
JadeServer64bit32 (JadeServer) >> sbClassFrom: @14 line 14
JadeServer64bit32 (JadeServer) >> sbRunClassTests: @4 line 4
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
Fixed in 3.0.35. Part of the many perils of trying to maintain two separate browsers is that stuff like this has to be maintained in two ways.  When the base is rowanized and we can get rid of the dictionary browser, stuff like this will go away.
