### ISSUE TITLE
SUnit tab issues

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#179]
I'm looking at RowanSample1Test class.

- [x] the icon that has the window with the sunit (debug) gets an error:
                RowanMethodService does not understand #methodName
This is a useful function so I'd like to see it working... but at least function-not-implemented would be better for first oscar.

The following are additional annoying quibbles:

- [x] When you first select the SUnit tab, the little running guy icon is disabled.  Since that's "run all", iI shouldn't need to select a particular test to enable it.  

- [ ] if you select something, click on a different tab then back; whatever was selected before is selected but the icons are all disabled.

**Comment by ericwinger** [comment]
1. @LisaAlmarode I think the toolbar button is working but perhaps I'm misunderstanding. Can you recheck or show me what you're clicking? Thanks. 
2. This is weird. I've looked at it before but I'll take another look. 
3. probably related to 2.

**Comment by ericwinger** [comment]
@LisaAlmarode #2 & #3 have something to do with tab focus. Most everything I've tried simply refuses to cooperate - ie it didn't work. Even pre-selecting a method in the list, hooking into focus events and doing explicit enables. 

I'm tempted to remove them and let people use the pop-up menu items. Thoughts?

**Comment by LisaAlmarode** [comment]
I rather like the icons on the side there.  Focus not an urgent issue, so I'll say we can live with this.

**Comment by ericwinger** [comment]
Think I've finally solved the focus issues. Should be fixed in 3.0.69.

**Comment by LisaAlmarode** [comment]
Points #2 and #3 are now working, as is #1; but I filed issue #494 on the enable/disable of the icons.
