### ISSUE TITLE
Method pane colors

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#182]
I'm getting weird behavior with the method pane colors and the associated menu items.

- [x] I'm not seeing a change of color when I edit a method.  I thought it used to do that. I suspect this is intentional behavior, that yellow is set for both no change and unsaved edits; or possibly the color change is too subtle.

- [x] With the method selected, and not being entirely sure what the meanings of the colors are, I went to change them using the menu items (on preferences).  Color for unsaved edits. Unfortunately it doesn't look like it highlights the selected color.  

- [x] Closed the color selector without saving and now the unsaved edits are gray.

- [x] Now when I try to open color for unsaved edits, it gets a jadeite error: "UndefinedObject does not understand #value" .

- [x] The color change for Compile errors needs to be much more noticable.  It looks yellow and you have to really be sharp to see it's not the same yellow.   It's not at all noticeable enough

**Comment by ericwinger** [comment]
> I'm not seeing a change of color when I edit a method. 
The method list browser & debugger don't appear to change color. The project browser does. I'll see if I can get that fixed in 3.0.37.

**Comment by ericwinger** [comment]
I fixed the color save problems so that those who wish to have different colors can. But let's open a new bug after some review if we still want the default colors to change.
