### ISSUE TITLE
Protect against unloading Rowan?

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#184]
Unloading Rowan (and most likely Cypress, STON, and Tonel) project will result in unpredictable behavior. Should ``Unload Project`` be disabled for those projects?

**Comment by LisaAlmarode** [comment]
You can only unload Rowan as SystemUser and no one should do ordinary development as SystemUser.  SystemUser has much power to shoot self in foot and/or head.  So I don't think it's worth adding complexity for this.  Reassign to Dale in case he has an opinion.

**Comment by ericwinger** [comment]
Works for me.

**Comment by ericwinger** [comment]
Closing, no action taken.
