### ISSUE TITLE
icon in console menu

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#186]
The icon for the sunit browser isn't right in the runtime.  I suggest removing it if it's work to fix.

![image](https://user-images.githubusercontent.com/13142166/45586363-42494900-b8c4-11e8-8f29-def8c22e89b9.png)

**Comment by ericwinger** [comment]
Not yet sure why the .exe can't find the icon so it's getting removed. It was rather an albatross anyway. Fixed in 3.0.37
