### ISSUE TITLE
Need to add Package to Rowan Project Changes list

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#302]
Currently the lists are Type, Class, Selector, Detail. 

Don't think it's a must have for alpha.

**Comment by LisaAlmarode** [comment]
Moving a method between packages in rowan-hybrid (as of 3.2.12) shows up as an addition plus a removal, which is not very helpful.  This might be worth doing for end 2022.

**Comment by ericwinger** [comment]
Package names are shown. Added a few tests also - one for moving a method between packages.
