### ISSUE TITLE
Need to handle confirm: 

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#303]
Type
```
self confirm: 'hi' 
```
in a workspace. That should raise a Jadeite dialog which the user can return true or false.

**Comment by dalehenrich** [comment]
Moved here from Rowan issues list ... not sure if you still want to do this or not

**Comment by LisaAlmarode** [comment]
I don't have a strong feeling - it's kind of gui-ish for rowan; Eric, you can close, defer, or fix as you feel appropriate.

**Comment by ericwinger** [comment]
As of 3.0.77, should be able to send ``confirm:`` ``inform:`` and ``inspect`` and Jadeite will raise the appropriate dialog box or inspector. 

![image](https://user-images.githubusercontent.com/36212516/64446766-806be980-d08e-11e9-8fa3-d3e0fe593afa.png)
