### ISSUE TITLE
Ability to rename a class 

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#306]
If you select a class in the Rowan browser, then select it again, it becomes editable. 

This is a nice refactoring feature, but would require additional Rowan support to make it work such as find/rename references to class. 

It may be easiest to disable edit capability of class names until this is available.

**Comment by dalehenrich** [comment]
in case this issue is still needed

**Comment by ericwinger** [comment]
Yes, I'd like to have a class rename feature. I'll bump it up on my to-do list.

**Comment by ericwinger** [comment]
Fixed with comments in #439

**Comment by LisaAlmarode** [comment]
Found one fairly ugly problem reported as #499.

Also - minor but ought to be fixed - if you rename a purple extension class, it works just fine, but it doesn't update the classes pane correctly. You see both the old and new purple class names, and clicking on the old one causes an oop? to appear and methods have empty source.

In general though it seems very nice.

**Comment by LisaAlmarode** [comment]
I do notice that the previous versions of the class (classHistory) appear to be gone after a rename.  This is probably also a bug since gemstone class names are not important in class history relationships.

**Comment by ericwinger** [comment]
@LisaAlmarode Is this part of your [comment](https://github.com/GemTalk/Jadeite/issues/306#issuecomment-517820137) fixed? 

> Also - minor but ought to be fixed - if you rename a purple extension class, it works just fine, but it doesn't update the classes pane correctly. You see both the old and new purple class names, and clicking on the old one causes an oop? to appear and methods have empty source.

**Comment by ericwinger** [comment]
@LisaAlmarode Regarding https://github.com/GemTalk/Jadeite/issues/306#issuecomment-517822950 ...
It appears that the classHistory is not retained after a rename.  Hard to show with pictures, but here is what I see after renaming class Aaa to Bbb
```
Aaa classHistory aClassHistory( Aaa, Aaa)
Bbb classHistory aClassHistory( Bbb)
```

I'm going to close this issue. If you feel the renamed class should retain it's history the fix is probably in Rowan.

**Comment by LisaAlmarode** [comment]
The class history thing is a separate issue, related to issue #510.  Otherwise rename is working fine, although at some point I'll complain about it telling me 0 methods were changed and the spurious double quote that appears within the recompile-failed dialog.
