### ISSUE TITLE
Changes browser inspect menu item error dialog

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#309]
I was browsing around in changes browser and selected a removal... there's a pop up menu with inspect and browse... I clicked inspect... 

and got an error dialog saying "MCRemoval does not understand #inspect".  In fact I get a similar error dialog for every change in the changes list.  

This is with Jadeite 2.0 and the latest candidate branch (1a3301e).   
I don't think it's necessarily a build-breaking type crisis that should delay work on the actual release...

**Comment by dalehenrich** [comment]
in case this is still relevant

**Comment by LisaAlmarode** [comment]
There's no inspect option as of 3.0.74, and the three browse menu items all, reasonably, say they can't browse.
