### ISSUE TITLE
Use `System needsCommit` to decide whether `Commit current transaction?` question actually needs to be asked

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/Jadeite#310]
I appreciate the question when I have work that would be lost if I don't commit. But the dialog is just annoying when I have committed before exiting image:

![image](https://user-images.githubusercontent.com/623951/39962037-b4f700c0-55f8-11e8-9062-1c57c80563e7.png)

**Comment by LisaAlmarode** [comment]
It is annoying to commit, then immediately exit and get the question.  
However, it's not an actual problem and I'm used to being annoyed by this in GBS.
It gets a little more annoying if you have autocommit on.  Shouldn't it automatically commit if so?

However, I don't think this is necessarily worth a lot of effort.

**Comment by jgfoster** [comment]
I believe that this dialog only comes up if there are unsaved changes. So, what changes happen behind the scenes after you do an explicit commit?

**Comment by ericwinger** [comment]
``JadeiteTranscript>>onCloseRequested`` did not send ``System>>needsCommit`` but does as of 3.0.77.
