### ISSUE TITLE
Jadeite: Can't get a rich inspector on basic object types

### ISSUE THREAD

**Issue by ablakeman** [GemTalk/Jadeite#312]
For most objects, Jade provides a fully featured inspector:

![image](https://user-images.githubusercontent.com/16963117/40395955-5d265f78-5ddf-11e8-9840-979d219bd0d1.png)

If you inspect a basic class such as Integer or String, you get a very basic inspector

![image](https://user-images.githubusercontent.com/16963117/40396031-c53c2ba6-5ddf-11e8-8a58-c073322f5d92.png)

It would be helpful to have the fully featured inspector available to classes such as String so that it's easier to debug their contents.

**Comment by dalehenrich** [comment]
this might still be an issue, I think

**Comment by LisaAlmarode** [comment]
String inspectors were added a whiles back before 3.0.74.  There's not much to say about an integer but it does provide the oop
