### ISSUE TITLE
ProcessorScheduler is deadlocked

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#50]
Running Oscar remotely is much slower than in the office, and if I click too fast (say, I realized I meant to open the project list but opened the projects browser instead) I get these deadlock messages; and I have to logout before I can do anything further.  On looking at the stack, it's not clear that it can't be worked around... 

a ThreadError occurred (error 2366), reason:rtErrSchedulerDeadlocked, The ProcessorScheduler is deadlocked

OffsetError (AbstractException) >> _signalWith: @5 line 25
OffsetError (AbstractException) >> signal @2 line 47
SortedCollection (Object) >> _error:args: @15 line 11
SortedCollection (Object) >> _errorIndexOutOfRange: @2 line 6
SortedCollection >> at: @4 line 12
SortedCollection (SequenceableCollection) >> removeAtIndex: @2 line 6
ProcessorScheduler >> _findReadyProcess @31 line 28
ProcessorScheduler >> _reschedule @2 line 6
ProcessorScheduler >> _waitOnSema: @8 line 8
Semaphore >> wait @12 line 15
Semaphore >> critical: @2 line 5
TranscriptStreamPortable >> nextPut: @3 line 3
TranscriptStreamPortable (Stream) >> cr @3 line 5
RwGitTool >> performOnServer:logging: @5 line 26
RwGitTool >> performGitCommand:in:worktree:with:logging: @13 line 9
RwGitTool >> performGitCommand:in:with: @2 line 4
RwGitTool >> gitlogIn:with: @2 line 3
RwGitTool >> gitcommitShaIn: @4 line 5
RwProject >> repositoryCommitId @10 line 8
RowanProjectService >> repositorySha @3 line 3
RowanProjectService >> rowanSkew @3 line 3
RowanProjectService >> sha: @3 line 6
[] in  ExecBlock1 (RowanProjectService) >> projects @7 line 8
Array (SequenceableCollection) >> collect: @9 line 16
RowanProjectService >> projects @3 line 3
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
@LisaAlmarode This code goes through an old code path to get to the server via the ``transport`` instance variable in RowanService. Newer code in the browser goes through paths that prevent duplicate calls to the server by use of a browser flag ``inUpdate``. In theory, this kind of problem would be eliminated once the remaining paths through the old code are removed. 

I've been slowly eliminating these paths and here are the methods I have left to remove: 
![image](https://user-images.githubusercontent.com/36212516/44482940-8ff0cf80-a5fe-11e8-99a8-1897d29d575f.png)

Once done, I'll ask you to retest.

**Comment by ericwinger** [comment]
Believe this will be ready for testing in 3.0.20. Because some underlying 'old' service structure was removed, may have introduced some obscure brokenness, especially in dictionary browser.

**Comment by LisaAlmarode** [comment]
in 3.0.22, I reenabled transcript writes to make things slow, and clicked madly around.  
It was very solid... a couple of errors (index out of bounds and something not found), during some period of time where I just started new actions randomly as fast as I could, to stress the system.  So I was just about to call this fixed... it's so good now... when I did managed to get an error.

If this stack isn't immediately useful, then go ahead and reclose.  

a ThreadError occurred (error 2366), reason:rtErrSchedulerDeadlocked, The ProcessorScheduler is deadlocked
ThreadError (AbstractException) >> _signalWith: @6 line 25
ThreadError (AbstractException) >> signal @2 line 47
ProcessorScheduler >> _findReadyProcess @30 line 26
ProcessorScheduler >> _reschedule @2 line 6
ProcessorScheduler >> _waitOnSema: @8 line 8
Semaphore >> wait @12 line 15
Semaphore >> critical: @2 line 5
TranscriptStreamPortable >> nextPut: @3 line 3
TranscriptStreamPortable (Stream) >> cr @3 line 5
RwGitTool >> performOnServer:logging: @5 line 26
RwGitTool >> performGitCommand:in:worktree:with:logging: @13 line 9
RwGitTool >> performGitCommand:in:with: @2 line 4
RwGitTool >> gitlogIn:with: @2 line 3
RwGitTool >> gitcommitShaIn: @4 line 5
RwProject >> repositoryCommitId @10 line 8
RowanProjectService >> repositorySha @3 line 3
RowanProjectService >> isSkew @6 line 3
RowanProjectService >> basicRefresh @9 line 6
RowanProjectService >> refresh @2 line 2
RowanProjectService class >> newNamed: @5 line 6
[] in  ExecBlock1 (RowanBrowserService) >> updateProjects @3 line 5
SortedCollection (SequenceableCollection) >> collect: @9 line 16
RowanBrowserService >> updateProjects @7 line 5
RowanBrowserService >> update @2 line 3
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @6 line 11
OrderedCollection (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
Closed in favor of a more complete solution in #128.
