### ISSUE TITLE
Method changes not making project italic (dirty)

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#51]
When you add a method, the browser is updated to show that the project is dirty.

however, if your remove a method, remove a method category and contained methods, or move a method between categories, it doesn't make the project italic/dirty until you click around a bit to see the packages are italic and Jade>refresh to update the project.

Adding a new class does not update the project to show dirtiness too.

I think the underlying objects are correct and it's just not updateing the display except for added methods.

**Comment by ericwinger** [comment]
I think method-level dirtiness is important for the first release. Class dirtiness would be nice but less important (imho). 

I filed this as a rowan feature request some time ago - 
https://github.com/dalehenrich/Rowan/issues/276

**Comment by ericwinger** [comment]
This might be related to #130

**Comment by ericwinger** [comment]
@LisaAlmarode  Can you recheck this? I believe it is fixed.

**Comment by LisaAlmarode** [comment]
Verified four operations on instance and class side in PB, the project and get dirty.
