### ISSUE TITLE
Adding a new subclass reload project: get walkback

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#52]
I added a new subclass, but didn't save or commit.  I'm in the project list browser with the package containing the new subclass selected, so I see the list of classes including the new subclass.  Select a class other than the transient one, and the Class Definition tab is selected.

Then, load the project.  This removed class is still there but not really "there", and various activities gets a walkback, 

a MessageNotUnderstood occurred (error 2010), a UndefinedObject does not understand  #'comment'

MessageNotUnderstood >> defaultAction @2 line 3
MessageNotUnderstood (AbstractException) >> _signalWith: @5 line 25
MessageNotUnderstood (AbstractException) >> signal @2 line 47
UndefinedObject (Object) >> doesNotUnderstand: @9 line 10
UndefinedObject (Object) >> _doesNotUnderstand:args:envId:reason: @7 line 12
RowanClassService >> basicRefreshFrom: @4 line 5
RowanClassService >> refreshFrom: @2 line 3
RowanClassService >> updateClass @4 line 5
RowanClassService >> update @2 line 3
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @5 line 10
OrderedCollection (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
Hmm, I can't get to the Jadeite bug. Submitted a Rowan bug to Dale which happens when I do a rowan load. https://github.com/dalehenrich/Rowan/issues/330

**Comment by dalehenrich** [comment]
@ericwinger I point out in dalehenrich/Rowan#330 ... that you are not using the laster version of the master branch  and when you created your eric branch you picked up a [typo (that was fixed back in June)](https://github.com/dalehenrich/RowanSample1/commit/da00868e988a55f0dfd2e35817f4b560152d96fa) in the Default.ston file... The latest version of the master branch does not have the issue ...

**Comment by LisaAlmarode** [comment]
This looks like a lot like #127.  Using the scenario in this bug, if I do something to refresh the list of classes, everything else seems to works fine.  I suspect this bug is fixed and #127 is a just a refresh issue; and I'll close it optimistically.

**Comment by LisaAlmarode** [comment]
This is open but a compliciated issue involving gemstone behavior wrt transient symbol list.  Low priorty, so defer and document.
