### ISSUE TITLE
First click onto menu bar in a browser; get truncated menu

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#72]
If I've got two browsers open, and focus is in on one of them, and I click on an item in the menu bar of the other browser, I reliably get an oddly truncated menu.  It seems I do this a lot.

This may be a windows dolphin unsolvable problem.  It's not horrible.... but it's not pretty, either.  

![image](https://user-images.githubusercontent.com/13142166/44305696-ca264c80-a332-11e8-8f7a-cc517659d5aa.png)

![image](https://user-images.githubusercontent.com/13142166/44305700-ede99280-a332-11e8-933e-8e670a937f7e.png)

**Comment by ericwinger** [comment]
@LisaAlmarode  Could you recheck this? Since you filed this bug, I took out a refresh that happened every time a window received focus. Since I can't reproduce this, it's slightly possible that that change fixed the bug.

**Comment by LisaAlmarode** [comment]
I haven't been able to reproduce this in recent versions.
