### ISSUE TITLE
debugger ad-hoc execution broken

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#77]
- In a debugger type in this code
``3+4 ``
- Highlight code and Ctrl-D to display the results
- [x] result of execution is the string not the result. 
``3+4
3+4``
- [x] execution string is still highlighted. The result should be highlighted.

**Comment by ericwinger** [comment]
Ctrl-E (execute in Dolphin) erases the highlighted code and replaces it with a red ENQ
Ctrl-Q (inspect in Dolphin) erases the highlighted code and replaces it with a red DC1

**Comment by ericwinger** [comment]
using the toolbar widgets, I see the previously broken behavior where the context variables aren't recognized. ``undefined symbol``

**Comment by ericwinger** [comment]
checked in change to use the parent presenter's context object when doing ad-hoc executions in the code source pane.  sha 4484a9b3

**Comment by jgfoster** [comment]
Added menus to main window so they are intercepted before getting to Scintilla.

**Comment by LisaAlmarode** [comment]
This was okay in the previous test, but in v3.0.21, the debugger now is showing red EOT on control D, X, and Q.  The menu bar and popup menu items work okay.

Control D, X, and Q are also broken in the transcript and other code panes.

**Comment by ericwinger** [comment]
@LisaAlmarode  can you retest this in 3.0.25. It appears to work for me in both the development environment and executable.

**Comment by LisaAlmarode** [comment]
Ctrl+D doesn't work, but Ctrl+d does work.  I'm not a keyboard shortcut person; the menus say "Ctrl+D" and I see D and I detect this is an uppercase letter.  
Or... this is the same in VW as well, so perhaps it's normal to use D to mean d? 
Or is there something else that I'm missing?  
Perhaps the menus should be fixed, for someone like me who might use that information?

**Comment by jgfoster** [comment]
When describing keys on the keyboard, it is traditional to match what is typically etched on the key. Unless something is quite unusual, I suspect that your keyboard has 'D' as the label for the key between 'S' and 'F' and there is no 'd' on your keyboard. To indicate that one is to press the key labeled 'Shift', one specifies that as another key press. So when asked to press [Ctrl]+[D], you instead pressed [Ctrl]+[Shift]+[D], which is not what was expected. For an example, see the menu on any GUI application. Attached is a screen shot of Chrome on macOS.

![screen shot 2018-09-03 at 3 58 28 pm](https://user-images.githubusercontent.com/1577872/45002995-3a1f0e80-af92-11e8-8785-684ad056bee0.png)

**Comment by LisaAlmarode** [comment]
Seems odd to reduce the data density of helpful information in the name of tradition... but perhaps it's since I've most recently been documenting VSD, which is a GUI app that identifies keyboard shortcuts with case precision.  But, then... VSD is its own thing.  I suppose if you can't pattern-match D and d it would make a difference. 
Anyway, I don't mind since I don't use them anyway; if the rest of the world is happy...
