### ISSUE TITLE
Browser frame method should open Projects browser first

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#78]
- Selecting a stack frame
- In the context menu choose `Browser Frame Method`

This should open the projects browser first if it's a rowanized method. 

``JadeiteProjectsBrowserPresenter>>updateAfterFindClass:`` is a good starting point to make this work.

**Comment by ericwinger** [comment]
Browse Object Class in variables menu -  same thing.

**Comment by ericwinger** [comment]
Browse Frame Method was fixed some time ago. 

We're getting rid of the dictionary browser in issue #217 so this becomes a mute issue.

**Comment by ericwinger** [comment]
Marking this closed as the integrated project/dictionary browser is close to its first release. 
https://github.com/GemTalk/Jadeite/commit/92c4f91c37872a2102b628d3c50187b3514a0084

**Comment by LisaAlmarode** [comment]
In 3.0.74, if you execute Array new at: 4, and in the debugger select the Array >> at:  frame,  and browse frame method; it opens a dictionary browser.  Browse object class also opens a Dictionary Browser.

I think that it should open a project browser even on a non-rowanized method now.

**Comment by ericwinger** [comment]
@LisaAlmarode Pretty sure that the dictionary browser references were removed in a commit subsequent to 3.0.74. Please check again in 3.0.75. 
https://github.com/GemTalk/Jadeite/commit/9e315770ecccc44617e49b8fafb953a524d7d64e or https://github.com/GemTalk/Jadeite/commit/f453e0c4c69044a5dd1d2db3d499359c296a219e

**Comment by LisaAlmarode** [comment]
In 3.0.75 it is bringing up the PB.
