### ISSUE TITLE
Take out "debugger switch" 

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#80]
In a recent commit, I added the ability to switch between the old debugger (JadeDebugger) and the new debugger @jgfoster is working on. (RowanDebugger). 

Before we release a version of Oscar to the customer, and when the new debugger is "good enough", take this out and default to the new debugger. 

- [x] Remove transcript menu item
- [x] Default to RowanDebugger

**Comment by ericwinger** [comment]
Removed switch, always use new debugger. 

Done so we can ship to customer soon. Fixed in 3.0.16

**Comment by jgfoster** [comment]
And the pressure is on!

**Comment by LisaAlmarode** [comment]
I think this is not closed and ought to be on the to-do list, since, in fact, it represents a task that is not done.  I suppose it could be deferred.

**Comment by LisaAlmarode** [comment]
The switch isn't in 3.0.38 so calling this fixed.
