### ISSUE TITLE
Need Oscar that will work in the same server as Alpha

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#94]
- [ ] Need to package new and old JadeServer & service classes separately. 
- [ ] Rename JadeServer & service classes
- [ ] Update name references to resolve all JadeServer & service classes through Rowan (to allow "slide-in" services for future)

**Comment by ericwinger** [comment]
@dalehenrich Think we still need to support Alpha now? If not, I'll close this issue.

**Comment by dalehenrich** [comment]
no longer an issue ...

**Comment by ericwinger** [comment]
Retiring.
